/**
 * Electron Bootstrap — Shell Layer Entry Point
 *
 * This file is package.json#main in production builds.
 * It decides whether to load the code bundle or built-in code.
 *
 * WARNING: Changes to this file will change the Shell fingerprint,
 * triggering a full update for all users. Modify with care.
 *
 * Generated by @electron-hot-updater/cli
 */

const { app } = require('electron')
const path = require('path')
const fs = require('fs')
const Module = require('module')

// --- Dev/Prod isolation ---
if (!app.isPackaged) {
  const devName = app.getName() + '-Dev'
  app.setName(devName)
  app.setPath('userData', path.join(app.getPath('appData'), devName))
}

// --- Constants ---
const SHELL_FINGERPRINT = '__SHELL_FINGERPRINT__' // Replaced at build time by ehu fingerprint --inject
const USER_DATA = app.getPath('userData')
const BUNDLE_DIR = path.join(USER_DATA, 'code-bundle-' + SHELL_FINGERPRINT)
const META_FILE = path.join(BUNDLE_DIR, 'meta.json')
const CRASH_FILE = path.join(USER_DATA, 'code-bundle-crash.json')
const INSTALL_ID_FILE = path.join(USER_DATA, 'code-bundle-install-id.txt')
const BUILTIN_ROOT = path.join(__dirname, '..')
const MAX_CRASH = 3
const CRASH_WINDOW = 30000

// --- Crash protection ---

function isCrashLooping() {
  try {
    if (!fs.existsSync(CRASH_FILE)) return false
    const { crashes = [] } = JSON.parse(fs.readFileSync(CRASH_FILE, 'utf-8'))
    return crashes.filter(t => Date.now() - t < CRASH_WINDOW).length >= MAX_CRASH
  } catch { return false }
}

function recordCrash() {
  try {
    const data = fs.existsSync(CRASH_FILE)
      ? JSON.parse(fs.readFileSync(CRASH_FILE, 'utf-8'))
      : { crashes: [] }
    data.crashes = [...data.crashes, Date.now()].slice(-MAX_CRASH)
    fs.writeFileSync(CRASH_FILE, JSON.stringify(data))
  } catch {}
}

// --- Clean stale bundles ---

function cleanStaleBundles() {
  try {
    const entries = fs.readdirSync(USER_DATA, { withFileTypes: true })
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      if (entry.name.startsWith('code-bundle-') && entry.name !== 'code-bundle-' + SHELL_FINGERPRINT) {
        const stalePath = path.join(USER_DATA, entry.name)
        console.log('[ehu] Cleaning stale bundle:', entry.name)
        try { fs.rmSync(stalePath, { recursive: true, force: true }) } catch {}
      }
    }
  } catch {}
}

// --- Windows pending bundle ---

function applyPendingBundle() {
  const BUNDLE_PENDING = BUNDLE_DIR + '-pending'
  if (!fs.existsSync(BUNDLE_PENDING)) return
  try {
    const BUNDLE_BACKUP = BUNDLE_DIR + '-backup'
    if (fs.existsSync(BUNDLE_BACKUP)) fs.rmSync(BUNDLE_BACKUP, { recursive: true, force: true })
    if (fs.existsSync(BUNDLE_DIR)) fs.renameSync(BUNDLE_DIR, BUNDLE_BACKUP)
    fs.renameSync(BUNDLE_PENDING, BUNDLE_DIR)
    if (fs.existsSync(BUNDLE_BACKUP)) fs.rmSync(BUNDLE_BACKUP, { recursive: true, force: true })
    console.log('[ehu] Applied pending code bundle')
  } catch (e) {
    console.error('[ehu] Failed to apply pending bundle:', e.message)
    try { if (fs.existsSync(BUNDLE_PENDING)) fs.rmSync(BUNDLE_PENDING, { recursive: true, force: true }) } catch {}
  }
}

// --- Resolve bundle ---

function resolveBundle() {
  applyPendingBundle()
  cleanStaleBundles()

  try {
    if (!fs.existsSync(META_FILE)) return null
    const meta = JSON.parse(fs.readFileSync(META_FILE, 'utf-8'))

    console.log('[ehu] Found code bundle: v' + meta.version + ', fingerprint=' + SHELL_FINGERPRINT)

    // Reinstall detection via executable ctime
    let currentInstallId = ''
    try { currentInstallId = String(fs.statSync(process.execPath).ctimeMs) } catch {}
    let lastInstallId = ''
    try { lastInstallId = fs.existsSync(INSTALL_ID_FILE) ? fs.readFileSync(INSTALL_ID_FILE, 'utf-8').trim() : '' } catch {}
    if (lastInstallId && currentInstallId && lastInstallId !== currentInstallId) {
      console.log('[ehu] Reinstall detected, clearing code bundle')
      try { fs.rmSync(BUNDLE_DIR, { recursive: true, force: true }) } catch {}
      return null
    }

    // Entry file check
    const bundleEntry = path.join(BUNDLE_DIR, 'main.bundle.js')
    if (!fs.existsSync(bundleEntry)) {
      console.log('[ehu] Code bundle missing main.bundle.js, skipping')
      return null
    }

    // Crash protection
    if (isCrashLooping()) {
      console.log('[ehu] Crash loop detected, reverting to built-in code')
      try { fs.rmSync(BUNDLE_DIR, { recursive: true, force: true }) } catch {}
      try { fs.unlinkSync(CRASH_FILE) } catch {}
      return null
    }

    console.log('[ehu] Loading code bundle: v' + meta.version)
    return { path: BUNDLE_DIR, version: meta.version }
  } catch (e) {
    console.error('[ehu] Failed to read code bundle:', e.message)
    return null
  }
}

// --- Bootstrap ---

const bundle = resolveBundle()

if (bundle) recordCrash()

// Save install ID for reinstall detection
try {
  const ctime = String(fs.statSync(process.execPath).ctimeMs)
  fs.writeFileSync(INSTALL_ID_FILE, ctime)
} catch {}

// Environment variables for the main process
process.env.CODE_ROOT = bundle ? bundle.path : BUILTIN_ROOT
process.env.SHELL_ELECTRON_DIR = __dirname
process.env.SHELL_ROOT = BUILTIN_ROOT
process.env.USING_CODE_BUNDLE = bundle ? 'true' : 'false'
process.env.CODE_BUNDLE_VERSION = bundle ? bundle.version : ''
process.env.SHELL_FINGERPRINT = SHELL_FINGERPRINT

// Code bundle mode: set NODE_PATH so external modules resolve from install dir
if (bundle) {
  const appNodeModules = path.join(BUILTIN_ROOT, 'node_modules')
  process.env.NODE_PATH = [appNodeModules, process.env.NODE_PATH].filter(Boolean).join(path.delimiter)
  Module._initPaths()
}

// Load main process
if (bundle) {
  console.log('[ehu] code bundle v' + bundle.version)
  require(path.join(bundle.path, 'main.bundle.js'))
} else {
  require(path.join(__dirname, '..', '.vite', 'build', 'main.js'))
}
